"""add pet_count to Cat model

Revision ID: 8bd77b209d2c
Revises: 375fb38c48ca
Create Date: 2023-01-28 10:38:21.895974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd77b209d2c'
down_revision = '375fb38c48ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('pet_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'pet_count')
    # ### end Alembic commands ###
